### PR TITLE
Added Navigation Model to IWeb

### PR DESCRIPTION
**Pull request by MathijsVerbeeck**
Added base functionalities for #212 

Web:
- Add navigation nodes to the top navigation and quicklaunch
- Delete all navigation nodes
- Add child nodes
- Move child nodes after a specific child node
- Update existing navigation node

### CODE REVIEW

**Comment by jansenbe** [comment]
Awesome work @MathijsVerbeeck !! Thanks for helping out growing PnP Core SDK 💪

**Comment by matsla** [comment]
@jansenbe when will the added navigation model to IWeb be released?

**Comment by jansenbe** [comment]
@matsla , soon I hope, will try to process this one over the weekend or early next week.

**Comment by jansenbe** [comment]
@MathijsVerbeeck : just merged this nicely implemented PR, well done! Thanks 🚀💪👍

**Pull request merged**
