### PR TITLE
Add code to set sensitivity label to a group via updating associated site properties

### PR DESCRIPTION
**Pull request by wilecoyotegenius**
As per #1352, when creating a team site using TeamSiteOptions, sensitivity label is not getting correctly applied (it shows correctly in SPO Admin, but does not in Azure Portal nor in Graph API when querying the created group).

This PR modifies the team site creation process, by removing sensitivity label from 'creationOptions' and applying label to the group via updating associated site properties just after group creation.

### CODE REVIEW

**Comment by jansenbe** [comment]
Thanks for this fix @wilecoyotegenius ! I'll process your PR in the coming days, I'm just back from a break

**Comment by jansenbe** [comment]
@wilecoyotegenius: this change was merged, I added the needed test cases to ensure we cover this scenario.

@bricinocar: FYI

**Comment by wilecoyotegenius** [comment]
@jansenbe Glad I could help :)

**Comment by bricenocar** [comment]
Thanks a lot @jansenbe !

**Pull request merged**
