### PR TITLE
ALM feature.

### LINKED ISSUE #215: Create models for ALM APIs
## Category

- [x] Feature request

## Describe the feature

- Add the ability to call the ALM APIs as descirbed in the article: [https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?tabs=sprest](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?tabs=sprest)
- Unit Tests for calling the APIs
- If there are special requirements or permissions with this model, add to the documentation

## Contributing

We encourage and welcome contributions for the PnP Core SDK, if you are interested, please comment below to engage with the team. If you want to learn about how to get started, please refer to this guide: [https://pnp.github.io/pnpcore/articles/contributor/readme.html](https://pnp.github.io/pnpcore/articles/contributor/readme.html)

The team is constantly improving the guidance on supporting contributors, if you have any feedback or need help please feel free to start a discussion.

### PR DESCRIPTION
**Pull request by s-KaiNet**
This PR adds ALM support to the PnP Core. 
As discussed in the linked issue:

- two extension methods were added to support different app catalogs - `GetTenantAppManager` and `GetSiteCollectionAppManager`
- [SyncToTeams](https://github.com/pnp/pnpframework/blob/8827e09d41bfbc38a600e482b844111f0e3efed0/src/lib/PnP.Framework/ALM/AppManager.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L551) methods were excluded until upstream SharePoint API will be [fixed](https://github.com/SharePoint/sp-dev-docs/issues/7441)
- tenant and site collection app managers use base `AppManager` class with core functionality
- additional endpoints for tenant app manager were implemented based on the [metadata](https://s-kainet.github.io/sp-rest-explorer/#/_api/web/TenantAppCatalog). 
- the developer API remains consistent with the previous [AppManager](https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework/ALM/AppManager.cs), however also adds new features, like using app instances to call `Deploy`, `Install`, etc. methods directly.

Feel free to add any comments, suggestions, corrections, etc. even if it requires a full code rewrite from my side. This is my very first big PR to the PnP Core library, so I'm just learning :)

Closes #215

### CODE REVIEW

**Comment by jansenbe** [comment]
Awesome work @s-KaiNet . I plan to review and process this PR in the coming days, super happy you've been helping out here 💪🥇🚀🎉

**Comment by jansenbe** [comment]
@s-KaiNet : just merged your PR. I'm truly impressed by the work you've done!! Very clean and well written code, super test coverage and documentation 🎉 Congrats on this great PR. 

Hope you enjoyed doing it, you've managed to find your way in PnP Core SDK but if you've ideas about possible improvements then don't hesitate to call them out.

I could successfully run all but one test against my lab tenant: `GetTenantAppCatalogUrlReturnsNullTest` will only work when the tenant does not yet have an app catalog. I think that test will always fail for the majority of PnP Core SDK contributors, so for now I've commented out the test.

**Comment by s-KaiNet** [comment]
whoohoo! thanks @jansenbe!   

I have a bit more free time now and, maybe will have it for a few upcoming months, thus I'm glad to contribute to other PnP Core SDK areas as well. I see issues with the "help wanted" tag and planning to start working on any of them next. Most likely it will be #217. If you have any prioritization among issues, then please suggest which one should I work and I will work on it instead.

**Comment by DaleyKD** [comment]
@s-KaiNet : Thank you *SO* much, man. While my current project doesn't require anything with Apps, it is definitely something we use often. This is a great PR and I'm very thankful for it.

**Comment by jansenbe** [comment]
Thanks for the nice words @DaleyKD 👍 

@s-KaiNet : Contributing to PnP Core SDK is something you do in your spare time and I'm grateful you're helping out with PnP Core SDK. Feel free to pick any of the current issues or alternatively propose new areas: for example in the admin space there's still areas to cover. For the most important thing is that you **pick something you enjoy working on**.

The goal is to overtime make this an established .NET SDK for SharePoint+Teams development, without depending on the CSOM packages. In contrast with PnP Framework (and previously PnP Sites Core) the focus here is on performance, quality, test coverage and documentation...eventually this library will have enough features to allow for a deprecation of PnP Framework.

**Comment by s-KaiNet** [comment]
Thanks! Then the webhooks will be a nice feature to implement, cause I have some experience with hooks.

I love the idea of having a separate library to cover SharePoint and Teams. I remember some time ago there was a plan to open-source SharePoint CSOM. I can imagine how complicated the code inside CSOM is, how much legacy stuff is in there. It's not possible to contribute to such a library at all. Maybe it's good that it's not open-sourced :). From my understanding in the future, PnP Core SDK will become the "new CSOM" and "new PnP Framework". But a lot more stable and easier to contribute to. And that's cool.

**Pull request merged**
